[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

p1 = { path = "../p1" }
p2 = { path = "../p2" }
p3 = { path = "../p3" }